#!/usr/bin/env python3

import re
from typing import Literal

# Add context prefix - fastq
FQLR_CONTEXT_PREFIX = "fqr"  # Fastq (fastq row)
FQS_CONTEXT_PREFIX = "fqs"  # Fastq Set
FQLR_JOB_PREFIX = "fqj"  # Fastq Job Prefix

# https://regex101.com/r/zJRC62/1
ORCABUS_ULID_REGEX_MATCH = re.compile(r'^[a-z0-9]{3}\.[A-Z0-9]{26}$')

RGID_REGEX_MATCH = re.compile(r'[ACGT]+(?:\+[ACGT]+)?\.\d+\.[0-9A-Z_]+$')

RUN_QC_STATS_AWS_STEP_FUNCTION_ARN_ENV_VAR = "QC_STATS_AWS_STEP_FUNCTION_ARN"
RUN_NTSM_COUNT_AWS_STEP_FUNCTION_ARN_ENV_VAR = "NTSM_COUNT_AWS_STEP_FUNCTION_ARN"
RUN_NTSM_EVAL_X_AWS_STEP_FUNCTION_ARN_ENV_VAR = "NTSM_EVAL_X_AWS_STEP_FUNCTION_ARN"
RUN_NTSM_EVAL_X_Y_AWS_STEP_FUNCTION_ARN_ENV_VAR = "NTSM_EVAL_X_Y_AWS_STEP_FUNCTION_ARN"
RUN_FILE_COMPRESSION_AWS_STEP_FUNCTION_ARN_ENV_VAR = "FILE_COMPRESSION_AWS_STEP_FUNCTION_ARN"
RUN_READ_COUNT_AWS_STEP_FUNCTION_ARN_ENV_VAR = "READ_COUNT_AWS_STEP_FUNCTION_ARN"

DEFAULT_ROWS_PER_PAGE = 100

# Envs
EVENT_BUS_NAME_ENV_VAR = "EVENT_BUS_NAME"
EVENT_SOURCE_ENV_VAR = "EVENT_SOURCE"
EVENT_DETAIL_TYPE_FASTQ_STATE_CHANGE_ENV_VAR = "EVENT_DETAIL_TYPE_FASTQ_LIST_ROW_STATE_CHANGE"
EVENT_DETAIL_TYPE_FASTQ_SET_STATE_CHANGE_ENV_VAR = "EVENT_DETAIL_TYPE_FASTQ_SET_ROW_STATE_CHANGE"

# Add status to events
FastqStateChangeStatusEventsType = Literal[
    "FASTQ_CREATED",
    "FASTQ_DELETED",
    "READ_SET_ADDED",
    "READ_SET_DELETED",
    "FILE_COMPRESSION_UPDATED",
    "QC_UPDATED",
    "NTSM_UPDATED",
    "READ_COUNT_UPDATED",
    "LIBRARY_UPDATED",
    "FASTQ_IS_VALID",
    "FASTQ_IS_INVALID",
    "FASTQ_SET_UPDATED",
]

# Add status to fastq set events
FastqSetStateChangeStatusEventsType = Literal[
    "FASTQ_SET_CREATED",
    "FASTQ_SET_DELETED",
    "FASTQ_LINKED",
    "FASTQ_UNLINKED",
    "FASTQ_SET_IS_CURRENT",
    "FASTQ_SET_IS_NOT_CURRENT",
    "FASTQ_SET_ADDITIONAL_FASTQS_ALLOWED",
    "FASTQ_SET_ADDITIONAL_FASTQS_DISALLOWED",
    "FASTQ_SET_MERGED",
]
